# Generated by Django 5.2.2 on 2025-06-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
